module.exports = (agent, root) => ({
  list: agent.get(`${root}/bookings`),
    getDetails: agent.get(`${root}/bookings/:bookingId`),
      getSentenceDetail: agent.get(`${root}/bookings/:bookingId/sentenceDetail`),
      getMainOffence: agent.get(`${root}/bookings/:bookingId/mainOffence`),
      listAliases: agent.get(`${root}/bookings/:bookingId/aliases`),
      listContacts: agent.get(`${root}/bookings/:bookingId/contacts`),
      listAdjudications: agent.get(`${root}/bookings/:bookingId/adjudications`),
      getIepSummary: agent.get(`${root}/bookings/:bookingId/iepSummary`),

      listScheduledVisits: agent.get(`${root}/bookings/:bookingId/visits`),
         listScheduledVisitsToday: agent.get(`${root}/bookings/:bookingId/visits/today`),
      listAppointments: agent.get(`${root}/bookings/:bookingId/appointments`),
        listAppointmentsTodays: agent.get(`${root}/bookings/:bookingId/appointments/today`),
        listAppointmentsThisWeek: agent.get(`${root}/bookings/:bookingId/appointments/thisWeek`),
        listAppointmentsNextWeek: agent.get(`${root}/bookings/:bookingId/appointments/nextWeek`),
      getAccountBalances: agent.get(`${root}/bookings/:bookingId/balances`),
      listActivities: agent.get(`${root}/bookings/:bookingId/activities`),
        listActivitiesToday: agent.get(`${root}/bookings/:bookingId/activities/today`),
      listEvents: agent.get(`${root}/bookings/:bookingId/events`),
        listEventsToday: agent.get(`${root}/bookings/:bookingId/events/today`),
        listEventsThisWeek: agent.get(`${root}/bookings/:bookingId/events/thisWeek`),
        listEventsNextWeek: agent.get(`${root}/bookings/:bookingId/events/nextWeek`),
      listCaseNotes: agent.get(`${root}/bookings/:bookingId/caseNotes`),
        countCaseNotesByType: agent.get(`${root}/bookings/:bookingId/caseNotes/:type/:subType:/count`),
        getCaseNoteDetail: agent.get(`${root}/bookings/:bookingId/caseNotes/:caseNoteId`),
      listAlerts: agent.get(`${root}/bookings/:bookingId/alerts`),
        getAlertDetails: agent.get(`${root}/bookings/:bookingId/alerts/:alertId`),
      listAssessments: agent.get(`${root}/bookings/:bookingId/assessment/:assessmentCode`),
        getAssessmentDetail: agent.get(`${root}/bookings/:bookingId/assessment/:assessmentCode`),
});
