defaults: &defaults
  working_directory: ~/app
  docker:
  - image: circleci/node:10.15.3-browsers

version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Update npm
        command: 'sudo npm install -g npm@latest'
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: Install Dependencies
        command: npm ci
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
        - node_modules
    - run:
        command: |
          npm run build
          DATE=$(date '+%Y-%m-%d')
          export BUILD_NUMBER=${DATE}.${CIRCLE_BUILD_NUM}
          export GIT_REF="$CIRCLE_SHA1"
          npm run record-build-info
    - persist_to_workspace:
        root: .
        paths:
        - node_modules
        - build-info.json
        - assets/stylesheets

  build_docker:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build container and publish to docker hub
          command: |
            APP_VERSION=$(egrep buildNumber build-info.json  | awk -F"\"" '{print $4}')
            GIT_REF=$(egrep gitRef build-info.json  | awk -F"\"" '{print $8}')

            docker build --rm=false . \
               --build-arg BUILD_NUMBER=$APP_VERSION \
               --build-arg GIT_REF=$GIT_REF \
               --tag "mojdigitalstudio/nomis-reports:$APP_VERSION" \
               --label "maintainer=feedback@digital.justice.gov.uk" \
               --label "build.number=$CIRCLE_BUILD_NUM" \
               --label "build.url=$CIRCLE_BUILD_URL" \
               --label "build.gitref=$GIT_REF"

            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag mojdigitalstudio/nomis-reports:$APP_VERSION mojdigitalstudio/nomis-reports:latest
            docker push mojdigitalstudio/nomis-reports:$APP_VERSION
            docker push mojdigitalstudio/nomis-reports:latest

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - build_docker:
          requires:
          - build
          filters:
            branches:
              only: master
