let refData = {};

refData.build = x => {
  switch (`${x}`) {
    case 'MUSC': return 'Muscular';
    case 'PROP': return 'Proportional';
    default: return x;
  }
};

refData.courtOutcome = x => {
  switch (`${x}`) {
    case '': return 'Male'; // TODO: WTF???case "5600": return "civil Term Imposed";
    case "5601": return "civil Remand";
    case "5602": return "Civil Contempt Purged";
    case "MERGE": return "Merged Record";
    case "1002": return "Imprisonment";
    case "1003": return "Detained during HM Pleasure";
    case "1004": return "Restriction Order";
    case "1005": return "Borstal Training";
    case "1006": return "Detention Centre";
    case "1007": return "Detention";
    case "1008": return "Hospital Order";
    case "1009": return "Care Order";
    case "1010": return "Community Service";
    case "1011": return "Attendance Centre";
    case "1012": return "Supervision Order";
    case "1013": return "Probation Order";
    case "1014": return "Guardianship Order";
    case "1015": return "Fine";
    case "1016": return "Bound Over";
    case "1017": return "Absolute Discharge";
    case "1018": return "Conditional Discharge";
    case "1019": return "Discharged";
    case "1021": return "No Order Made";
    case "1022": return "Youth Custody";
    case "1024": return "Young Offenders Institution";
    case "1025": return "Referred Voluntary Measures";
    case "1026": return "Admonished";
    case "1027": return "Sentence Accumulated";
    case "1028": return "Subsequently Varied";
    case "1029": return "Order Revoked";
    case "1030": return "Order Varied (Scotland)";
    case "1031": return "Order Extended (Scotland)";
    case "1032": return "Order Amended (Scotland)";
    case "1034": return "Dismissed with Disgrace from HM Forces";
    case "1035": return "Dismissed from HM Forces";
    case "1036": return "Reduced to the Ranks";
    case "1037": return "Forfeiture of Seniority";
    case "1038": return "Severe Reprimand";
    case "1039": return "Reprimand";
    case "1040": return "Order to Continue";
    case "1046": return "Varied on Appeal";
    case "1049": return "Substituted";
    case "1051": return "Loss of Privilege";
    case "1052": return "Curfew Order";
    case "1054": return "Non Standard Foreign Disposal";
    case "1055": return "Unserved from Original Sentence";
    case "1056": return "Detained in Place approved by Sec. Of State";
    case "1057": return "No Separate Penalty";
    case "1058": return "Training School Order (NI)";
    case "1062": return "Jersey Parish Hall Voluntary Supervision";
    case "1063": return "Recognizance Paid (Guernsey)";
    case "1064": return "Official Caution (Verbal)(Guernsey)";
    case "1065": return "Official Caution (Written)(Guernsey)";
    case "1066": return "Placed on the Black List (Guernsey)";
    case "1067": return "Bound Over to Leave the Island within 3 days";
    case "1068": return "Caution Imposed (Scotland)";
    case "1070": return "Estreat";
    case "1071": return "Fine (Jersey)";
    case "1073": return "Detained without Limit of Time";
    case "1074": return "Criminal Procedure (Scotland) Act 1975";
    case "1075": return "Order under Prisoner & Criminal Proceedings (Scotland) Act 1993 s.16";
    case "1076": return "Warning (Scotland)";
    case "1077": return "Youth Custody (Guernsey)";
    case "1078": return "Supervised Attendance Order";
    case "1079": return "Supervision and Treatment Order";
    case "1080": return "Secure Training Order";
    case "1081": return "Detention and Training Order";
    case "1082": return "Restriction of Liberty Order";
    case "1083": return "Reparation Order";
    case "1084": return "Action Plan Order";
    case "1085": return "Parenting Order";
    case "1086": return "Drug Treatment and Testing Order";
    case "1087": return "No Action on Breach";
    case "1088": return "Hospital & Limitation Directions";
    case "1089": return "Suspended Sentence Supervision Order";
    case "1090": return "Supervision Order (Young Offenders)";
    case "1091": return "Detained during Secretary of State's pleasure (NI)";
    case "1092": return "Young Offenders Centre (NI)";
    case "1093": return "Juvenile Justice Centre (NI)";
    case "1094": return "Recognizance Estreated";
    case "1096": return "Custody Probation Order (NI)";
    case "1097": return "Referral Order";
    case "1098": return "Community rehabilitation order";
    case "1099": return "Community punishment order";
    case "1100": return "Exclusion order";
    case "1101": return "Drug Abstinence order";
    case "1102": return "Community punishment and rehabilitation order";
    case "1103": return "Civil Diligence";
    case "1104": return "Enhanced Probation Order (Drugs)";
    case "1105": return "Fine or Imprisonment";
    case "1106": return "Fine or YOI";
    case "1107": return "Fine or Supervised Attendance Order";
    case "1108": return "Disposal Unknown";
    case "3045": return "Appeal Dismissed";
    case "3047": return "Restraining Order Protection from Harassment";
    case "3049": return "Proceeding Invalidated by Statutory Declaration";
    case "3050": return "Reduced Disqualification from Driving after Completing Course";
    case "3051": return "Reduced Disqualification from Driving - special reasons or mitigating circumstances";
    case "3052": return "Sex Offenders Notice";
    case "3053": return "Secure Accommodation Order";
    case "3054": return "Forfeiture";
    case "3055": return "Deprivation";
    case "3056": return "Confiscation";
    case "3061": return "Supervised Release Order (Scotland)";
    case "3062": return "Driving Licence Revoked";
    case "3063": return "Disposal Order (NI)";
    case "3064": return "DestNItion Order (NI)";
    case "3065": return "Certificate of Realisation (NI)";
    case "3066": return "Allowed to drive pending appeal (NI)";
    case "3067": return "Non-molestation Order (NI)";
    case "3068": return "Football Banning Order";
    case "3069": return "Disqualified from working with children";
    case "3070": return "Disqualified from Driving - Obligatory";
    case "3071": return "Disqualified from Driving - Discretionary";
    case "3072": return "Disqualified from Driving - Points (Totting)";
    case "3073": return "Disqualified from Driving until Ordinary Test Passed";
    case "3074": return "Disqualified from Driving until Extended Test Passed";
    case "3075": return "Disqualification Suspended Pending Appeal on Imposition";
    case "3076": return "Disqualification Suspended Pending Appeal Subsequent to Imposition";
    case "3077": return "Dog to be kept on lead at all times";
    case "3079": return "Supplementary Information to Charge";
    case "3080": return "Anti-Social Behaviour Order";
    case "3081": return "Restraining order Sexual offence";
    case "3082": return "Contingent Destruction Order";
    case "3083": return "Financial circumstances order";
    case "3084": return "Individual support order";
    case "3085": return "Notification order - sex offender";
    case "3086": return "Sexual offences prevention order";
    case "3087": return "Foreign travel order";
    case "3088": return "Risk of sexual harm order";
    case "3089": return "Interim notification order";
    case "3090": return "Interim sexual offences prevention order";
    case "3091": return "Interim Risk of sexual harm order";
    case "3092": return "Interim Secure Accommodation Order";
    case "3093": return "Appeal Withdrawn";
    case "3094": return "Disqualified from Driving non-motoring offence";
    case "3095": return "Disqualified from Driving - Vehicle Used In Crime";
    case "3096": return "Interim Disqualification from Driving";
    case "3097": return "Intervention Order (Scotland)";
    case "3501": return "Dealt with for Original Offence";
    case "3502": return "Dealt with for breach";
    case "3503": return "Order to give Personal Details e.g. Date of Birth and/or Sex";
    case "3504": return "Certificate of Tainted Acquittal";
    case "3508": return "No Endorsement (Special Reasons)";
    case "3509": return "No Disqualification (Special Reasons or Mitigating Circumstances)";
    case "3510": return "Order to Produce Driving Licence";
    case "3512": return "No Compensation Reasons";
    case "4001": return "Committed to Crown Court for Sentence";
    case "4004": return "Sentence Postponed";
    case "4005": return "Sentence Deferred";
    case "4006": return "Remitted to Children's Hearing";
    case "4007": return "Remitted to High Court";
    case "4008": return "Remitted to Sheriff Court";
    case "4009": return "Transferred to High Court";
    case "4010": return "Withdrawn (Other)";
    case "4011": return "Remittal for Sentence on Conditional Bail";
    case "4012": return "Remittal for Sentence in Custody";
    case "4013": return "Remittal for Sentence Unconditional Bail";
    case "4014": return "Commit to Crown Court for Sentence Unconditional Bail";
    case "4015": return "Commit to Crown Court for Sentence Conditional Bail";
    case "4016": return "Commit to Crown Court for Sentence in Custody";
    case "4017": return "Commit to Crown Court for Sentence in Custody with Direction to Release on Bail";
    case "4018": return "Discharged - Other";
    case "4020": return "Commit to Crown Court for Sentence - Remand to Local Authority Accommodation";
    case "4021": return "Commit to Crown Court for Sentence - Remand to Local Authority Secure Accommodation";
    case "4022": return "Extradited";
    case "4505": return "Warrant for Further Detention";
    case "4506": return "Adjournment";
    case "4507": return "Hearing Notice Criminal Case";
    case "4508": return "Summons Issued";
    case "4509": return "Youth Reporting Restrictions Dispensed With";
    case "1109": return "Penalty Notice";
    case "1110": return "Return to Detention";
    case "1111": return "Return to Prison";
    case "1112": return "Intermittent Custody Order";
    case "1113": return "NFA - No Court Appearance";
    case "1114": return "Prison Sentence - less than 12 months";
    case "1115": return "Suspended Imprisonment";
    case "1116": return "Community Order";
    case "1117": return "Conditional Caution Completed";
    case "1118": return "Conditional Caution Withdrawn";
    case "1119": return "Excise Penalty";
    case "1120": return "Referral to Scottish Ministry (Scotland)";
    case "1501": return "Recall to Prison";
    case "1505": return "Registration of Fixed Penalty";
    case "1507": return "Suspended Sentence Implemented";
    case "1508": return "Suspended Sentence Varied";
    case "1509": return "Detention in Default";
    case "1510": return "Imprisonment in default";
    case "1511": return "Attachment of Earnings Order";
    case "1512": return "Compulsory Work Order";
    case "1513": return "Clamping Order";
    case "1514": return "Benefits Deduction Order";
    case "2004": return "Not Guilty";
    case "2005": return "Acquitted";
    case "2006": return "Dismissed";
    case "2007": return "Adjourned sine die";
    case "2008": return "Lie on File";
    case "2009": return "Unfit to Plead";
    case "2010": return "Insane";
    case "2012": return "Committed to Military Escort";
    case "2015": return "Referral Discharge";
    case "2016": return "Not Proven";
    case "2017": return "Deserted Pro Loco";
    case "2018": return "Deserted Simpliciter";
    case "2023": return "Nolle Pros";
    case "2050": return "No Evidence Offered - Dismissed";
    case "2051": return "Withdrawn";
    case "2052": return "Not Proceeded with (Scotland)";
    case "2053": return "Discontinuance";
    case "2059": return "Carried Forward to Court Case";
    case "2060": return "Replaced With Another Offence";
    case "2061": return "Proceedings Stayed";
    case "2062": return "Aggravation by committing offence while on Bail (Scotland)";
    case "2063": return "Withdrawn - Final";
    case "2064": return "Judge Rules No Case to Answer";
    case "2065": return "Defendant Deceased";
    case "2066": return "Discharged - Final";
    case "2067": return "Community Service Order discharged";
    case "2068": return "Conviction Quashed";
    case "2501": return "Jury Discharged from Giving a Verdict, having reached a Verdict on another count";
    case "2503": return "Defendant Committed Suicide";
    case "2505": return "Wasted Costs Order Against";
    case "2507": return "Bail Appeal Withdrawn";
    case "2508": return "Summons Not Served";
    case "2509": return "Warrant Not Executed";
    case "2511": return "Power of Arrest";
    case "2514": return "Jury Discharged, unable to reach a Verdict";
    case "3002": return "Disqualified from being Company Director";
    case "3006": return "Deportation Recommended";
    case "3007": return "Disqualified from Driving";
    case "3008": return "Driving Licence Endorsed";
    case "3010": return "Legal Aid Contribution";
    case "3011": return "Costs";
    case "3012": return "Compensation";
    case "3013": return "Restitution";
    case "3014": return "Back Duty";
    case "3016": return "Forfeiture of Recognisance";
    case "3018": return "Pardoned";
    case "3019": return "Sentence Deferred From";
    case "3020": return "Order for Dog to be Neutered";
    case "3021": return "Order for Destruction of Dog";
    case "3022": return "Disqualification from Possessing Dog";
    case "3025": return "Disqualification From Keeping";
    case "3026": return "Reinstated Lie on File";
    case "3027": return "Reinstated Adjourned Sine Die";
    case "3028": return "Disqualification Limited to";
    case "3029": return "R Period Extended";
    case "3030": return "Driving Licence Restored with effect from";
    case "3031": return "Jersey Early Return of Driving Licence";
    case "3032": return "Disqualified (Scotland) From Holding";
    case "3033": return "Dog to be Muzzled at all Times";
    case "3034": return "Order to keep Dog under Control";
    case "3035": return "Firearm Certificate Revoked or cancelled";
    case "3038": return "Existing Guernsey Probation Order Varied";
    case "3039": return "Dismissed under the Probation of Offenders Law";
    case "3041": return "Licensed Premises Exclusion Order";
    case "3042": return "Resulting from Original Conviction of";
    case "3044": return "Appeal Pending";
    case "4501": return "Remanded??";
    case "DA": return "For Pre-Sentence Reports";
    case "3004": return "Disqualified from Voting";
    case "3005": return "Disqualified from Being a Firearms Dealer";
    case "3009": return "Driving Licence Suspended Until Test Passed";
    case "3015": return "Forfeiture/Confiscation";
    case "3017": return "Sporting Event Exclusion Order";
    case "3036": return "Licence Restored";
    case "3037": return "Conditional Offer";
    case "3040": return "Attend Session on Alcohol Advice";
    case "3043": return "Each Charge";
    case "3046": return "Each Count";
    case "3048": return "Asset Confiscation";
    case "3057": return "Restriction Order (Football Spectators Act 1989)";
    case "3058": return "Extended Period of Licence";
    case "3059": return "Domestic Football Banning Order";
    case "3060": return "International Football Banning Order";
    case "3078": return "Travel Restriction Order";
    case "3513": return "Appeal Withdrawn";
    case "4019": return "Pre-sentence drug testing order";
    case "4502": return "Interim Secure Accommodation Order";
    case "4503": return "Add to Indictment Summary Offences Related to Offences Committed for Trial to Crown Ct under Sect 40 Criminal Justice Act 1988";
    case "4504": return "Committal/Transfers/Sending for Trial";
    case "4511": return "Consents Summary Trial - Guilty";
    case "4512": return "Consents Summary Trial Guilty- Election for Trial Withdrawn";
    case "4513": return "Consents Summary Trial - Not Guilty";
    case "4514": return "Consents Summary Trial Not Guilty - Election for Trial Withdrawn";
    case "4515": return "Elects Trial by Jury";
    case "4516": return "Elects Trial by Jury (Consent to Summary Trial Withdrawn)";
    case "4517": return "Indictable Only";
    case "4518": return "Justices Direct Trial by Jury";
    case "4519": return "Summary Trial - Indicated Guilty Either Way Offence";
    case "4520": return "Summary Trial - Guilty MCA Procedure";
    case "4521": return "Summary Trial - Guilty Summary Offence";
    case "4522": return "Summary Trial - Not Guilty";
    case "4523": return "Summary Trial - Not Guilty Entered by Court";
    case "4524": return "Summary Trial - Not Guilty, Guilty Plea Withdrawn";
    case "4525": return "Under appropriate level - Guilty";
    case "4526": return "Under appropriate level - Not Guilty";
    case "4527": return "Guilty Plea to Lesser/Alternative Offence Not Charged Accepted by Crown Court";
    case "4540": return "Remand in Custody (Medical/Psychiatric Supplementary Report)";
    case "4578": return "Guilty/Convicted in Absence";
    case "4579": return "Guilty/Convicted";
    case "4580": return "Not Guilty but Guilty of lesser Offence Not Charged at Crown Court";
    case "4581": return "Not Guilty but Guilty of lesser Offence on Judge's Direction";
    case "4591": return "Interim Sex Offender Order";
    case "5001": return "Disqualified from Driving and Licence Endorsed";
    case "5002": return "Preventative Detention";
    case "5003": return "Approved School";
    case "5004": return "Hard Labour";
    case "5005": return "Penal Servitude";
    case "5006": return "Corrective Training";
    case "5008": return "Industrial School";
    case "5009": return "Reform School";
    case "5010": return "Otherwise Dealt With";
    case "5012": return "Return to Borstal";
    case "5013": return "Return to Approved School";
    case "5014": return "Recorded Sentence of";
    case "5015": return "Prison Fee";
    case "5016": return "Committed to Care of Education Authority";
    case "5017": return "Committed to Community Home";
    case "5018": return "Return to Corrective Training";
    case "5019": return "Return to Detention Centre";
    case "5020": return "Aggravation";
    case "9999": return "Non Standard BRC Disposal";
    case "4510": return "Prohibition on Reporting (Juvenile in Proceedings)";
    case "4529": return "Remand on Conditional Bail (Defendant Absent)";
    case "4530": return "Remand on Conditional Bail";
    case "4531": return "Remand in Custody (Bail Refused)";
    case "4532": return "Remand in Custody Ancillary Results";
    case "4533": return "Remand in Custody with Direction to Release on Bail";
    case "4534": return "Remand in Custody after Bail Appeal by Prosecutor";
    case "4535": return "Remand in Custody to Customs Detention";
    case "4536": return "Remand in Custody to Hospital (Mental Health Act)";
    case "4537": return "Remand in Local Authority Accommodation (Bail Refused)";
    case "4538": return "Remand in Local Authority Accommodation with Bail Direction";
    case "4539": return "Remand in Secure Local Authority Accommodation";
    case "4541": return "Remand in Police Custody";
    case "4542": return "Remand on Unconditional Bail";
    case "4543": return "Remand on Unconditional Bail (Defendant Absent)";
    case "4544": return "Acceptance of Surety";
    case "4548": return "Remittal to Youth Court Conditional Bail";
    case "4549": return "Remittal to Youth Court in Custody";
    case "4550": return "Remittal to Youth Court in Local Authority Accommodation";
    case "4551": return "Remittal to Youth Court in Secure Local Authority Accommodation";
    case "4552": return "Remittal to Youth Court Unconditional Bail";
    case "4553": return "Case Rescheduled - Not bailed";
    case "4554": return "Case Rescheduled - Not bailed (Personal Service)";
    case "4555": return "Case Rescheduled - Defendant on Bail";
    case "4556": return "Case Rescheduled - Defendant on Bail (Personal Service)";
    case "4557": return "Rescheduling of Case to Reopen under s142 MCA";
    case "4558": return "Commit/Transfer/Send to Crown Court for Trial on Unconditional Bail";
    case "4559": return "Commit/Transfer/Send to Crown Court for Trial on Conditional Bail";
    case "4560": return "Commit/Transfer/Send to Crown Court for Trial in Custody";
    case "4561": return "Commit/Transfer/Send to Crown Court for Trial in Custody With Direction to Bail";
    case "4562": return "Commit/Transfer/Send to Crown Court for Trial in Local Authority Accommodation";
    case "4563": return "Commit/Transfer/Send to Crown Court for Trial in Secure Local Authority Accommodation";
    case "4564": return "Commit/Transfer/Send to Crown Court for Trial in Custody (Transfer Direction)";
    case "4565": return "Commit to Crown Court for Trial (Summary / Either Way Offences)";
    case "4570": return "Mental Health Commit to Crown Court for Restriction (Remand to Hospital)";
    case "4571": return "Mental Health Commit to Crown Court for Restriction (Remand to Prison)";
    case "4572": return "Bail Review Impose/Vary Conditions";
    case "4573": return "Bail Review - Order to Surrender";
    case "4574": return "Variation of Bail Conditions - Application by defendant";
    case "4575": return "Warrant for Offence Backed for Bail (Dated)";
    case "4576": return "Warrant for Offence Not Backed for Bail (Undated)";
    case "4577": return "Warrant for Offence Backed for Bail (Undated)";
    case "4582": return "Interim Hospital Order";
    case "4583": return "Hearing Removed";
    case "4584": return "Reopen Case";
    case "4585": return "Warrant of Arrest for Parent/Guardian";
    case "4586": return "Warrant for Arrest of Witness";
    case "4587": return "Remittal for Trial - Conditional Bail";
    case "4588": return "Remittal for Trial - In Custody";
    case "4589": return "Remittal for Trial - Unconditional Bail";
    case "4590": return "Interim Anti-social Behaviour Order";
    case "1001": return "Death";
    case "1020": return "Not Separately Dealt With";
    case "1041": return "Community Home";
    case "1042": return "Remand Home";
    case "1043": return "Residential Training";
    case "1044": return "Supervision Requirement";
    case "1047": return "To Effect Release on";
    case "1050": return "With Effect From";
    case "1059": return "Fit Person Order";
    case "1060": return "Matrimonial Protection Order";
    case "1061": return "Matrimonial Exclusion Order";
    case "1069": return "Jersey Parish Hall Caution";
    case "1072": return "Community Service Order as Condition of Probation";
    case "1503": return "Combination Order";
    case "1506": return "Sex Offender Order";
    case "2021": return "Caution to be of Good Behaviour";
    case "2054": return "No Jurisdiction";
    case "2055": return "No Result Available";
    case "2512": return "Order Discharged";
    case "2513": return "Not Tried - Certified Insane before Arraignment";
    case "3001": return "Criminal Bankruptcy";
    case "3003": return "Disqualified from Public Office";
    case "5500": return "Immigration Detainee";
    case "5501": return "Immigration Bail";
    case "5502": return "Immigration Decision to Deport";
    case "3112": return "Taken into consideration (TIC)";
    case "3100": return "Interim ASBO";
    case "3514": return "Adjourned for Consideration of an ASBO";
    case "0001": return "cr00263a";
    case "002": return "cr00623";
    case "003": return "cr00263c";
    case "1245": return "cr55555";
    case "1121": return "Indeterminate Sentence Minimum";
    case "3098": return "Financial Reporting Order";
    case "3099": return "Football Incident";
    case "3101": return "Unpaid Work Requirement";
    case "3102": return "Activity Requirement";
    case "3103": return "Programme Requirement";
    case "3104": return "Prohibited Activity Requirement";
    case "3105": return "Curfew Requirement";
    case "3106": return "Exclusion Requirement";
    case "3107": return "Residence Requirement";
    case "3108": return "Mental Health Treatment Requirement";
    case "3109": return "Drug Rehabilitation Requirement";
    case "3110": return "Alcohol Treatment Requirement";
    case "3111": return "Attendance Centre Requirement";
    case "AA": return "Autrefois Acquit";
    case "AC": return "Autrefois Convict";
    case "G": return "Guilty";
    case "NC": return "No Conviction";
    case "NGIS": return "Not Guilty By Reason of Insanity";
    case "NV": return "No Verdict";
    case "FPR": return "Proved (Magistrates' Court Only)";
    case "FNPR": return "Not Proved (Magistrates' Court Only)";
    case "GGRR": return "GGRR473 TEST";
    default: return x;
  }
};

refData.profile = (t,x) => {
  switch (`${t}_${x}`) {
    case "GLASS_Y": return "YES";
    case "GLASS_N": return "NO";
    case "CULT_MID": return "MID EASTERN";
    case "CULT_THA": return "THAI";
    case "CULT_SCT": return "SCOTTISH";
    case "CULT_IRS": return "IRISH";
    case "CULT_CHN": return "CHINISE";
    case "CULT_ENG": return "ENGLISH";
    case "CULT_MAL": return "MAYLASIAN";
    case "CULT_ABO": return "AUSTRALIAN ABORIGINAL";
    case "CULT_JAP": return "JAPANESE";
    case "LDIM_Y": return "YES";
    case "LDIM_N": return "NO";
    case "CITIZEN_UNK": return "UNKNOWN";
    case "CITIZEN_USA": return "UNITED STATES";
    case "HAIR_COLOR_BLO": return "Blond";
    case "CLEN_Y": return "Yes";
    case "CLEN_N": return "No";
    case "SEX_M": return "Male";
    case "SEX_B": return "Both";
    case "CITIZEN_RUS": return "RUSSIA";
    case "CITIZEN_UK": return "UNITED KINGDOM";
    case "SKIN_COMPLEX_CL": return "Clear";
    case "SKIN_COMPLEX_DRK": return "Dark";
    case "SKIN_COMPLEX_FAR": return "Fair";
    case "SKIN_COMPLEX_LBR": return "Light Brown";
    case "SKIN_COMPLEX_LGT": return "Light";
    case "SKIN_COMPLEX_MBR": return "Medium Brown";
    case "SKIN_COMPLEX_OLV": return "Olive";
    case "SKIN_COMPLEX_SAL": return "Sallow";
    case "SKIN_COMPLEX_YEL": return "Yellow";
    case "DEXTERITY_L": return "Left";
    case "BALD_BLD": return "Bald";
    case "BALD_NOT": return "Not Bald";
    case "BALD_PAR": return "Partially bald";
    case "BALD_REC": return "Receding Hairline";
    case "BALD_WIG": return "Wig";
    case "CITIZEN_AUS": return "AUSTRALIA";
    case "CITIZEN_CAN": return "CANADA";
    case "CITIZEN_CUB": return "CUBA";
    case "CITIZEN_FRE": return "FRANCE";
    case "CITIZEN_IND": return "INDIA";
    case "CITIZEN_IRI": return "IRELAND";
    case "CITIZEN_JAP": return "JAPAN";
    case "CITIZEN_OTH": return "OTHER";
    case "SKIN_COMPLEX_BLK": return "Black";
    case "LANGUAGE_JAP": return "Japanese";
    case "LANGUAGE_CHI": return "Chinese";
    case "OCCUPATION_SAL": return "Salesman";
    case "OCCUPATION_TD": return "Truck Driver";
    case "RACE_CAU": return "Caucasian (SAMPLE)";
    case "RACE_ORI": return "Oriental (SAMPLE)";
    case "CITIZEN_SCO": return "SCOTLAND";
    case "OCCUPATION_DOC": return "Doctor";
    case "OCCUPATION_PSY": return "Psychiatrist";
    case "OCCUPATION_PSC": return "Psychologist";
    case "OCCUPATION_SWK": return "Social Worker";
    case "HAIR_COLOR_GRY": return "Grey";
    case "HAIR_COLOR_WHI": return "White";
    case "LANGUAGE_DUT": return "Dutch";
    case "LANGUAGE_ENG": return "English";
    case "LANGUAGE_FRE": return "French";
    case "LANGUAGE_GER": return "German";
    case "MARITAL_STS_CL": return "Common Law";
    case "MARITAL_STS_DIV": return "Divorced";
    case "MARITAL_STS_MAR": return "Married";
    case "MARITAL_STS_SEP": return "Seperated";
    case "MARITAL_STS_WID": return "Widowed";
    case "OCCUPATION_RE": return "Realtor";
    case "RACE_BLK": return "Black (SAMPLE)";
    case "RACE_EI": return "Eastern Indian (SAMPLE)";
    case "RACE_UNK": return "Unknown (SAMPLE)";
    case "SKIN_COMPLEX_AVG": return "Average";
    case "RACE_MID": return "Middle Eastern";
    case "CULT_UNK": return "UNKOWN";
    case "CITIZEN_NZL": return "NEW ZEALAND";
    case "CULTURE_ENG": return "ENGLISH";
    case "CULTURE_ISH": return "IRISH";
    case "CULTURE_JAP": return "JAPANESE";
    case "CULTURE_CHN": return "CHINESE";
    case "CULTURE_THA": return "THAI";
    case "CULTURE_MID": return "MIDDLE EASTERN";
    case "CULTURE_RUS": return "RUSSIAN";
    case "CULTURE_GER": return "GERMAN";
    case "CULTURE_POL": return "POLISH";
    case "CULTURE_DUT": return "DUTCH";
    case "CULTURE_FRE": return "FRENCH";
    case "FACIAL_HAIR_NO": return "No Facial Hair";
    case "EYE_COLOR_BRO": return "Brown (SAMPLE)";
    case "HAIR_COLOR_BRO": return "Brown";
    case "HAIR_COLOR_BLK": return "Black";
    case "HAIR_COLOR_BLD": return "Bald";
    case "YOUTH?_Y": return "YES";
    case "YOUTH?_N": return "NO";
    case "YOUTH_INMATE_N": return "NO";
    case "ADULT_Y": return "YES";
    case "ADULT_N": return "NO";
    case "YOUTH_Y": return "Yes";
    case "TTEST_TT2": return "TEST2";
    case "APPEAR_N": return "No";
    case "APPEAR_Y": return "Yes";
    case "BUILD_FRAIL": return "Frail";
    case "BUILD_HEAVY": return "Heavy";
    case "BUILD_MEDIUM": return "Medium";
    case "BUILD_MUSC": return "Muscular";
    case "BUILD_OBESE": return "Obese";
    case "BUILD_PROP": return "Proportional";
    case "BUILD_SLIGHT": return "Slight";
    case "BUILD_SMALL": return "Small";
    case "BUILD_STOCKY": return "Stocky";
    case "BUILD_STOOPED": return "Stooped";
    case "BUILD_THIN": return "Thin";
    case "COMPL_ALBINO": return "Albino";
    case "COMPL_BLOTCHED": return "Blotched";
    case "COMPL_DARK": return "Dark";
    case "COMPL_DRAB": return "Drab";
    case "COMPL_FAIR": return "Fair";
    case "COMPL_FRECKLED": return "Freckled";
    case "COMPL_FRESH": return "Fresh";
    case "COMPL_HEAVY": return "Heavy";
    case "COMPL_NORMAL": return "Normal";
    case "COMPL_PALE": return "Pale";
    case "COMPL_POCKED": return "Pocked";
    case "COMPL_RUDDY": return "Ruddy";
    case "COMPL_SALLOW": return "Sallow";
    case "COMPL_WEATHERED": return "Weathered";
    case "COMPL_YELLOW": return "Yellow";
    case "DIET_CHFR": return "Medical - Cheese Free";
    case "DIET_DIAB": return "Medical - Diabetic";
    case "DIET_XXXX": return "Medical - Diet Abuse";
    case "DIET_FAT": return "Medical - Fat Free Diet";
    case "DIET_FFMK": return "Medical - Fat Free Milk Diet";
    case "DIET_FPFR": return "Medical - Fat/Pork Free";
    case "DIET_FIFR": return "Medical - Fish Free";
    case "DIET_FRY": return "Medical - Fry Free Diet";
    case "DIET_GLU": return "Medical - Gluten Free Diet";
    case "DIET_LAC": return "Medical - Lactose Free Diet";
    case "DIET_LCD": return "Medical - Low Cholesterol Diet";
    case "DIET_LFMA": return "Medical - Low Fat - Milk - Rice";
    case "DIET_LFAS": return "Medical - Low Fat - Rice Not Potato";
    case "DIET_LFSK": return "Medical - Low Fat - Sikh";
    case "DIET_LFD": return "Medical - Low Fat Diet";
    case "DIET_MLK": return "Medical - Milk Diet";
    case "DIET_MAOI": return "Medical - Mono Amine Oxidase Inhibitors";
    case "DIET_MOLF": return "Medical - Muslim - Low Fat";
    case "DIET_PKFR": return "Medical - Pork Free";
    case "DIET_HIN": return "Religion - Hindu";
    case "DIET_JEW": return "Religion - Jewish";
    case "DIET_MOR": return "Religion - Mormon";
    case "DIET_MOS": return "Religion - Muslim";
    case "DIET_SIKH": return "Religion - Sikh";
    case "DIET_AFRD": return "Voluntary - Afro-Caribbean";
    case "DIET_VXXX": return "Voluntary - Diet Abuse";
    case "DIET_EFPF": return "Voluntary - Egg/Fish/Pork Free";
    case "DIET_HAL": return "Voluntary - Halal Meat Only";
    case "DIET_SP/F": return "Voluntary - Normal Diet But Spice Free";
    case "DIET_PFFF": return "Voluntary - Pork Free/Fish Free";
    case "DIET_PFAS": return "Voluntary- Pork Free- Rice Not Potato";
    case "DIET_ASIA": return "Voluntary - Rice In Lieu Of Potatoes";
    case "DIET_VNAS": return "Voluntary - Rice In Lieu Of Potatoes";
    case "DIET_VGV": return "Voluntary - Vegan";
    case "DIET_VEFF": return "Voluntary - Vegetable/Egg/Fish Free";
    case "DIET_VGFF": return "Voluntary - Vegetarian - Fat Free";
    case "DIET_VGAS": return "Voluntary - Vegetarian - Rice Not Potato";
    case "DIET_VGSF": return "Voluntary - Vegetarian - Spice Free";
    case "DIET_VG1": return "Voluntary - Vegetarian With Fish";
    case "DIET_VG2": return "Voluntary - Vegetarian Without Fish";
    case "DIET_WID": return "Voluntary - West Indian";
    case "DNA_N": return "No";
    case "DNA_Y": return "Yes";
    case "DOMESTIC_NO": return "No";
    case "DOMESTIC_NA": return "Not Asked";
    case "DOMESTIC_NS": return "Not Stated";
    case "DOMESTIC_REF": return "Refused";
    case "DOMESTIC_YES": return "Yes";
    case "DOMVIC_NO": return "No";
    case "DOMVIC_NA": return "Not Asked";
    case "DOMVIC_NS": return "Not Stated";
    case "DOMVIC_REF": return "Refused";
    case "DOMVIC_YES": return "Yes";
    case "FACE_ANGULAR": return "Angular";
    case "FACE_BULLET": return "Bullet";
    case "FACE_OVAL": return "Oval";
    case "FACE_ROUND": return "Round";
    case "FACE_SQUARE": return "Square";
    case "FACE_TRIANGULAR": return "Triangular";
    case "FACIAL_HAIR_CLEAN SHAVEN": return "Clean Shaven";
    case "FACIAL_HAIR_BEARDED": return "Full Beard";
    case "FACIAL_HAIR_GOATEE": return "Goatee Beard";
    case "FACIAL_HAIR_MOUSTACHE": return "Moustache Only";
    case "FACIAL_HAIR_NA": return "Not Applicable (Female Offender)";
    case "FACIAL_HAIR_SIDEBURNS": return "Sideburns";
    case "HAIR_BALD": return "Bald";
    case "HAIR_BALDING": return "Balding";
    case "HAIR_BLACK": return "Black";
    case "HAIR_BLONDE": return "Blonde";
    case "HAIR_BROWN": return "Brown";
    case "HAIR_BRUNETTE": return "Brunette";
    case "HAIR_DARK": return "Dark";
    case "HAIR_DYED": return "Dyed";
    case "HAIR_GINGER": return "Ginger";
    case "HAIR_GREY": return "Grey";
    case "HAIR_LIGHT": return "Light";
    case "HAIR_MOUSE": return "Mouse";
    case "HAIR_RED": return "Red";
    case "HAIR_WHITE": return "White";
    case "IMM_N": return "No";
    case "IMM_Y": return "Yes";
    case "L_EYE_C_BLUE": return "Blue";
    case "L_EYE_C_BROWN": return "Brown";
    case "L_EYE_C_CLOUDED": return "Clouded";
    case "L_EYE_C_GREEN": return "Green";
    case "L_EYE_C_GREY": return "Grey";
    case "L_EYE_C_HAZEL": return "Hazel";
    case "L_EYE_C_MISSING": return "Missing";
    case "L_EYE_C_PINK": return "Pink";
    case "L_EYE_C_WHITE": return "White";
    case "LIST_REC_N": return "No";
    case "LIST_REC_Y": return "Yes";
    case "LIST_SUIT_N": return "No";
    case "LIST_SUIT_Y": return "Yes";
    case "R_EYE_C_BLUE": return "Blue";
    case "R_EYE_C_BROWN": return "Brown";
    case "R_EYE_C_CLOUDED": return "Clouded";
    case "R_EYE_C_GREEN": return "Green";
    case "R_EYE_C_GREY": return "Grey";
    case "R_EYE_C_HAZEL": return "Hazel";
    case "R_EYE_C_MISSING": return "Missing";
    case "R_EYE_C_PINK": return "Pink";
    case "R_EYE_C_WHITE": return "White";
    case "RELF_ADV": return "Adventist";
    case "RELF_AGNO": return "Agnostic";
    case "RELF_APO": return "Apostolic";
    case "RELF_ATHE": return "Atheist";
    case "RELF_BAHA": return "Ba'hai";
    case "RELF_BAPT": return "Baptist";
    case "RELF_BLAC": return "Black Muslim";
    case "RELF_BUDD": return "Buddhist";
    case "RELF_CALV": return "Calvinist";
    case "RELF_CCOG": return "Celestial Church of God";
    case "RELF_CE": return "Christadelphian";
    case "RELF_CHRST": return "Christian";
    case "RELF_CHSC": return "Christian Scientist";
    case "RELF_CINW": return "Church In Wales";
    case "RELF_COFE": return "Church of England (Anglican)";
    case "RELF_COFI": return "Church of Ireland";
    case "RELF_COFN": return "Church of Norway";
    case "RELF_COFS": return "Church of Scotland";
    case "RELF_CSW": return "Church of Sweden";
    case "RELF_CONG": return "Congregational";
    case "RELF_COPT": return "Coptic";
    case "RELF_DRU": return "Druid";
    case "RELF_EODX": return "Dutch Reform Church";
    case "RELF_EPIS": return "Episcopalian";
    case "RELF_ETHO": return "Ethiopian Orthodox";
    case "RELF_EVAN": return "Evangelical";
    case "RELF_GOSP": return "Gospel";
    case "RELF_GROX": return "Greek Orthodox";
    case "RELF_HARE": return "Hare Krishna";
    case "RELF_HIND": return "Hindu";
    case "RELF_JAIN": return "Jain";
    case "RELF_JEHV": return "Jehovah's Witness";
    case "RELF_JEW": return "Jewish";
    case "RELF_LUTH": return "Lutheran";
    case "RELF_METH": return "Methodist";
    case "RELF_MORM": return "Mormon";
    case "RELF_MOS": return "Muslim";
    case "RELF_NONC": return "Non Conformist";
    case "RELF_NONP": return "Non Permitted Religions";
    case "RELF_OTH": return "Other";
    case "RELF_PAG": return "Pagan";
    case "RELF_PARS": return "Parsi";
    case "RELF_PENT": return "Pentecostal";
    case "RELF_PRES": return "Presbyterian";
    case "RELF_PROT": return "Protestant";
    case "RELF_QUAK": return "Quaker";
    case "RELF_RAST": return "Rastafarian";
    case "RELF_RC": return "Roman Catholic";
    case "RELF_RUSS": return "Russian Orthodox";
    case "RELF_SALV": return "Salvation Army";
    case "RELF_SATN": return "Satanism";
    case "RELF_SCIE": return "Scientologist";
    case "RELF_SDAY": return "Seventh Day Adventist";
    case "RELF_SHIA": return "Shia Muslim";
    case "RELF_SHIN": return "Shintoist";
    case "RELF_SIKH": return "Sikh";
    case "RELF_SPIR": return "Spiritualist";
    case "RELF_SUNI": return "Sunni Muslim";
    case "RELF_TAO": return "Taoist";
    case "RELF_UNIF": return "Unification";
    case "RELF_UNIT": return "Unitarian";
    case "RELF_UR": return "United Reformed";
    case "RELF_UNKN": return "Unknown";
    case "RELF_WELS": return "Welsh Independent";
    case "RELF_ZORO": return "Zoroastrian";
    case "SEXO_BIS": return "Bisexual";
    case "SEXO_HET": return "Heterosexual / Straight";
    case "SEXO_HOM": return "Gay / Lesbian";
    case "SEXO_REF": return "Refused";
    case "SMOKE_N": return "No";
    case "SMOKE_Y": return "Yes";
    case "TAT_N": return "No";
    case "TAT_Y": return "Yes";
    case "RELF_NIL": return "No Religion";
    case "RELF_ORTH": return "Orthodox (Greek/Russian)";
    case "MARITAL_C": return "Co-habiting (living with partner)";
    case "MARITAL_D": return "Divorced or dissolved";
    case "MARITAL_M": return "Married or in civil partnership";
    case "MARITAL_N": return "Prefer not to say";
    case "MARITAL_P": return "Separated-not living with legal partner";
    case "MARITAL_S": return "Single-not married/in civil partnership";
    case "MARITAL_W": return "Widowed";
    case "CULTURE_SPA": return "SPANISH";
    case "EYE_COLOR_MISSING": return "Missing";
    case "EYE_COLOR_PINK": return "Pink";
    case "HAIR_COLOR_BALDING": return "Balding";
    case "HAIR_COLOR_BLONDE": return "Blonde";
    case "HAIR_COLOR_BROWN": return "Brown";
    case "HAIR_COLOR_BRUNETTE": return "Brunette";
    case "HAIR_COLOR_DARK": return "Dark";
    case "HAIR_COLOR_DYED": return "Dyed";
    case "HAIR_COLOR_GREY": return "Grey";
    case "HAIR_COLOR_LIGHT": return "Light";
    case "HAIR_COLOR_MOUSE": return "Mouse";
    case "HAIR_COLOR_MULTI": return "Multi-coloured";
    case "HAIR_COLOR_WHITE": return "White";
    case "HAIR_MULTI": return "Multi-coloured";
    case "ETHNIC_W2": return "Irish-White";
    case "ETHNIC_M1": return "White and Black Caribbean -mixed";
    case "ETHNIC_M2": return "White and Black African - Mixed";
    case "ETHNIC_M3": return "White and Asian - Mixed";
    case "ETHNIC_M9": return "Any other mixed background";
    case "ETHNIC_A2": return "Pakistani - Asian or Asian British";
    case "ETHNIC_A3": return "Bangladeshi - Asian or Asian British";
    case "ETHNIC_B1": return "Caribbean - Black or Black British";
    case "ETHNIC_B2": return "African - Black or Black British";
    case "ETHNIC_B9": return "Any other Black background";
    case "ETHNIC_O1": return "Chinese - Chinese or other ethnic group";
    case "ETHNIC_O9": return "Any other ethnic group";
    case "ETHNIC_NS": return "Not stated";
    case "REL_CATH": return "CATHOLIC";
    case "REL_ATH": return "ATHIEST";
    case "REL_NOND": return "NONDENOMINATIONAL";
    case "HAIR_CLR_BRN": return "Brown";
    case "HAIR_CLR_BLK": return "Black";
    case "HAIR_CLR_RED": return "Red";
    case "EYE_BRN": return "Brown";
    case "EYE_BLU": return "Blue";
    case "EYE_GRN": return "Green";
    case "CR_Y": return "YES";
    case "CR_N": return "NO";
    case "CR_U": return "UNKNOWN";
    case "DEX_L": return "LEFT";
    case "DEX_R": return "RIGHT";
    case "DEX_U": return "UNKNOWN";
    case "HANDICAP_YES": return "YES";
    case "HANDICAP_NO": return "NO";
    case "HAIR_CLR_BALD": return "Bald";
    case "WT_2": return "2";
    case "COMPLEXION_FAIR": return "FAIR";
    case "COMPLEXION_DARK": return "DARK";
    case "BLD_MED": return "Medium";
    case "BLD_OBS": return "Obese";
    case "BLD_HVY": return "Heavy";
    case "DEX_RIGHT": return "RIGHT";
    case "DEX_BOTH": return "BOTH";
    case "DEX_UNK": return "UNKNOWN";
    case "SJS_1": return "1";
    case "SJS_3": return "3";
    case "SCARS_Y": return "YES";
    case "SCARS_N": return "NO";
    case "WEAPONS_Y": return "YES";
    case "test_TEST": return "test";
    case "TEST4_Y": return "Yes";
    case "TEST4_N": return "No";
    case "CULTURE_AFR": return "AFRICAN/AMERICAN";
    case "JUV_MARK": return "MARK SKINNER";
    case "JUV_MACK": return "MACK BOYLE";
    case "CASE_DEREK": return "Derek Tangedal";
    case "CASE_VIPUL": return "Vipul Mishra";
    case "CASE_PETER": return "Peter Mak";
    case "MILTRY DISC_HON": return "HONOURABLE";
    case "MILTRY DISC_UNK": return "UNKNOWN";
    case "BLD_SLD": return "Slender";
    case "ETHNICITY_H": return "HISPANIC";
    case "ETHNICITY_NH": return "NON-HISPANIC";
    case "RELIGION_PROTESTANT": return "PROTESTANT";
    case "RELIGION_MUSLIM": return "MUSLIM";
    case "RELIGION_NON": return "NON-DENOMINATIONAL";
    case "RELIGION_ATHIEST": return "ATHIEST";
    case "RELIGION_UNKNOWN": return "UNKNOWN";
    case "ETHNIC_H": return "HISPANIC";
    case "FAT_V": return "Very";
    case "FAT_N": return "Not So Much";
    case "MEG_Y": return "YES";
    case "MEG_N": return "NO";
    case "AL_N": return "NO";
    case "SMOKER_Y": return "Yes";
    case "SMOKER_N": return "No";
    case "AL_UNK": return "UNKNOWN";
    case "EMP/SCHOOL_TSC": return "TRADE SCHOOL";
    case "ID MARKS_NO TAT": return "NO TATTOOS";
    case "EDUCATION_GRAD": return "GRADUATED";
    case "EDUCATION_DROP": return "DROP OUT";
    case "MILITARY_NO": return "NO";
    case "EMPLOYMENT_UN": return "UNEMPLOYED";
    case "EMPLOYMENT_EMP": return "EMPLOYED";
    case "TEST_YES": return "YES";
    case "TTEST_TT1": return "TEST1";
    case "EDUCA_HSG": return "High School Grad (SAMPLE)";
    case "EDUCA_BA": return "Bachelor of Arts Degree (SAMPLE)";
    case "NATIVE_METIS": return "METIS";
    case "NATIVE_SALISH": return "SALISH";
    case "RES_Y": return "Yes";
    case "RES_N": return "No";
    case "FACIAL_HAIR_CLEAN": return "Clean Shaven";
    case "RELF_DRC": return "Dutch Reform Church";
    case "RELF_SCGY": return "Scientology";
    case "RELF_URC": return "United Reform Church";
    case "RELF_WIND": return "Welsh Independent";
    case "EYE_COLOR_BLUE": return "Blue";
    case "EYE_COLOR_BROWN": return "Brown";
    case "EYE_COLOR_GREEN": return "Green";
    case "EYE_COLOR_GREY": return "Grey";
    case "EYE_COLOR_HAZEL": return "Hazel";
    case "NAT_PYF": return "French Polynesian";
    case "NAT_GABO": return "Gabonese";
    case "NAT_GAMB": return "Gambian";
    case "NAT_GE": return "Georgian";
    case "NAT_GERM": return "German";
    case "NAT_GHAN": return "Ghanaian";
    case "NAT_GI": return "Gibraltar";
    case "NAT_GREE": return "Greek";
    case "NAT_GL": return "Greenlandic";
    case "NAT_GREN": return "Grenadian";
    case "NAT_GLP": return "Guadeloupe";
    case "NAT_GU": return "Guamanian";
    case "NAT_GUAT": return "Guatemalan";
    case "NAT_GUIN": return "Guinean";
    case "NAT_GUYA": return "Guyanese";
    case "NAT_HAIT": return "Haitian";
    case "NAT_HOND": return "Honduran";
    case "NAT_HUNG": return "Hungarian";
    case "NAT_CT": return "I-Kiribati";
    case "NAT_ICE": return "Icelandic";
    case "NAT_INDI": return "Indian";
    case "NAT_INDO": return "Indonesian";
    case "NAT_IRAN": return "Iranian";
    case "NAT_IRAQ": return "Iraqi";
    case "NAT_ISRA": return "Israeli";
    case "NAT_ITAL": return "Italian";
    case "NAT_IVOR": return "Ivorian";
    case "NAT_JAM": return "Jamaican";
    case "NAT_JAP": return "Japanese";
    case "NAT_JORD": return "Jordanian";
    case "NAT_KAZA": return "Kazakhstani";
    case "NAT_KENY": return "Kenyan";
    case "NAT_SW": return "Kittitian or Nevisian";
    case "NAT_KUWA": return "Kuwaiti";
    case "NAT_KN": return "Kyrgyzstani";
    case "NAT_LA": return "Laotian";
    case "NAT_LATV": return "Latvian";
    case "NAT_LEBA": return "Lebanese";
    case "NAT_LIBE": return "Liberian";
    case "NAT_LIBY": return "Libyan";
    case "NAT_LIEC": return "Liechtensteiner";
    case "NAT_LITHU": return "Lithuanian";
    case "NAT_LUX": return "Luxembourger";
    case "NAT_MACE": return "Macedonian";
    case "NAT_MO": return "Mahoran";
    case "NAT_MG": return "Malagasy";
    case "NAT_MALA": return "Malaysian";
    case "NAT_MALD": return "Maldivian";
    case "NAT_ML": return "Malian";
    case "NAT_MALT": return "Maltese";
    case "NAT_MAR": return "Marshallese";
    case "NAT_MTQ": return "Martiniquais";
    case "NAT_MARI": return "Mauritanian";
    case "NAT_MAUR": return "Mauritian";
    case "NAT_MEXI": return "Mexican";
    case "NAT_MICR": return "Micronesian";
    case "NAT_MLAW": return "Malawian";
    case "NAT_MOLD": return "Moldovan";
    case "NAT_MONA": return "Monacan";
    case "NAT_MONGO": return "Mongolian";
    case "NAT_MS": return "Montserratian";
    case "NAT_MORO": return "Moroccan";
    case "NAT_MOTS": return "Motswana";
    case "NAT_MOZA": return "Mozambican";
    case "NAT_NAMI": return "Namibian";
    case "NAT_NAUR": return "Nauruan";
    case "NAT_NEPA": return "Nepalese";
    case "NAT_NCL": return "New Caledonian";
    case "NAT_NZEA": return "New Zealander";
    case "NAT_NICA": return "Nicaraguan";
    case "NAT_NIGERIA": return "Nigerian";
    case "NAT_NIGER": return "Nigerien";
    case "NAT_NIU": return "Niuean";
    case "NAT_VY": return "Ni-Vanuata";
    case "NAT_NFK": return "Norfolk Islander";
    case "NAT_NKOR": return "North Korean";
    case "NAT_NORW": return "Norwegian";
    case "NAT_OMAN": return "Omani";
    case "NAT_PAKN": return "Pakistani";
    case "NAT_PALA": return "Palauan";
    case "NAT_PSE": return "Palestinian";
    case "NAT_PANA": return "Panamanian";
    case "NAT_PNGU": return "Papua New Guinean";
    case "NAT_PARA": return "Paraguayan";
    case "NAT_PERU": return "Peruvian";
    case "NAT_PCN": return "Pitcairn Islander";
    case "NAT_POLE": return "Polish";
    case "NAT_PORTU": return "Portuguese";
    case "NAT_PRI": return "Puerto Rican";
    case "NAT_QUAT": return "Qatari";
    case "MARITAL_H": return "Separated/Divorced";
    case "MARITAL_R": return "Refused or unacceptable answer";
    case "HAIRSTYLE_AFRO": return "Afro-ed hair";
    case "HAIRSTYLE_BALD": return "Balding";
    case "HAIRSTYLE_CNRD": return "Corn rowed";
    case "HAIRSTYLE_CPAR": return "Centre parting";
    case "HAIRSTYLE_CROP": return "Close cropped";
    case "HAIRSTYLE_DDLK": return "Dreadlocked";
    case "HAIRSTYLE_LONG": return "Long haired";
    case "HAIRSTYLE_MEDM": return "Medium";
    case "HAIRSTYLE_MULT": return "Multiple styles";
    case "HAIRSTYLE_PERM": return "Permed/Curly";
    case "HAIRSTYLE_RECE": return "Receding";
    case "HAIRSTYLE_SPAR": return "Side parting";
    case "HAIRSTYLE_THIN": return "Thinning";
    case "LOCN_Y": return "Yes";
    case "LOCN_N": return "No";
    case "POL_Y": return "Yes";
    case "POL_N": return "No";
    case "INVP_Y": return "Yes";
    case "INVP_N": return "No";
    case "INVI_Y": return "Yes";
    case "INVI_N": return "No";
    case "MEDIA_Y": return "Yes";
    case "MEDIA_N": return "N";
    case "HAIR_CLR_GING": return "Ginger";
    case "CULTURE_SCT": return "SCOTTISH";
    case "CULTURE_EIN": return "EASTERN INDIAN";
    case "CULTURE_DAN": return "DANISH";
    case "EYE_COLOR_GRN": return "Green (SAMPLE)";
    case "YOUTH_INMATE_Y": return "YES";
    case "RACE_HIS": return "Hispanic";
    case "REL_BUD": return "BUDDHIST";
    case "ETHNIC_W9": return "Any other white background";
    case "ETHNIC_A9": return "Any other Asian background";
    case "CULT_GER": return "GERMAN";
    case "CULT_RUS": return "RUSSIAN";
    case "CULT_EIN": return "EASTERN INDIAN";
    case "EYE_COLOR_BLU": return "Blue (SAMPLE)";
    case "SEX_F": return "Female";
    case "SKIN_COMPLEX_DBR": return "Dark Brown";
    case "SKIN_COMPLEX_MED": return "Medium";
    case "DEXTERITY_R": return "Right";
    case "CITIZEN_CHI": return "CHINA";
    case "CITIZEN_MEX": return "MEXICO";
    case "OCCUPATION_LAB": return "Laborer";
    case "OCCUPATION_LAW": return "Lawyer";
    case "HAIR_COLOR_RED": return "Red";
    case "LANGUAGE_SPA": return "Spanish";
    case "MARITAL_STS_SIN": return "Single";
    case "SKIN_COMPLEX_ALB": return "Albino";
    case "CULTURE_GRK": return "GREEK";
    case "CULTURE_KOR": return "KOREAN";
    case "CULTURE_ITL": return "ITALIAN";
    case "CULTURE_NAT": return "NATIVE AMERICAN";
    case "YOUTH_N": return "No";
    case "REL_PROT": return "PROTESTANT";
    case "HAIR_CLR_BND": return "Blond";
    case "WT_XXX": return "POUNDS";
    case "DEX_B": return "BOTH";
    case "WT_1": return "1";
    case "COMPLEXION_MED": return "MEDIUM";
    case "DEX_LEFT": return "LEFT";
    case "SJS_2": return "2";
    case "WEAPONS_N": return "NO";
    case "JUV_JACK": return "JACK SKINNER";
    case "MILTRY DISC_DIS": return "DISHONORABLE";
    case "RELIGION_CATHOLIC": return "CATHOLIC";
    case "ETHNIC_N": return "NON-HISPANIC";
    case "AL_Y": return "YES";
    case "ID MARKS_TAT": return "TATTOOS";
    case "MILITARY_YES": return "YES";
    case "TEST_NO": return "NO";
    case "NATIVE_CREE": return "CREE";
    case "BUILD_FAT": return "Fat";
    case "EYE_COLOR_CLOUDED": return "Clouded";
    case "EYE_COLOR_WHITE": return "White";
    case "HAIR_COLOR_BLACK": return "Black";
    case "HAIR_COLOR_GINGER": return "Ginger";
    case "ETHNIC_W1": return "British-White";
    case "ETHNIC_A1": return "Indian - Asian or Asian British";
    case "BLD_FAT": return "Fat";
    case "BLD_FRAIL": return "Frail";
    case "BLD_MUSCULAR": return "Muscular";
    case "BLD_NORMAL": return "Normal";
    case "BLD_PROP": return "Proportional";
    case "BLD_SLIGHT": return "Slight";
    case "BLD_SMALL": return "Small";
    case "BLD_STOCKY": return "Stocky";
    case "BLD_STOOPED": return "Stooped";
    case "BLD_THIN": return "Thin";
    case "RELF_CHRANG": return "Anglican";
    case "RELF_CHRBAPT": return "Baptist";
    case "RELF_CHRCE": return "Church of England";
    case "RELF_CHRCHDN": return "Christadelphian";
    case "RELF_CHRCHSC": return "Christian Scientist";
    case "RELF_CHRCHWA": return "Church in Wales";
    case "RELF_CHRCI": return "Church of Ireland";
    case "RELF_CHRCN": return "Church of Norway";
    case "RELF_CHRCS": return "Church of Scotland";
    case "RELF_CHRCSW": return "Church of Sweden";
    case "RELF_CHREODX": return "Ethiopian Orthodox";
    case "RELF_CHREPIS": return "Episcopalian";
    case "RELF_CHRJEHV": return "Jehovahs Witness";
    case "RELF_CHRLUTH": return "Lutheran";
    case "RELF_CHRMETH": return "Metodist";
    case "RELF_CHRMORM": return "Church of Jesus Christ of latterday St's";
    case "RELF_CHROCR": return "Other Christian Religion";
    case "RELF_CHRORTH": return "Orthodox (Greek/Russian)";
    case "RELF_CHRPENT": return "Pentecostal";
    case "RELF_CHRPRES": return "Presbyterian";
    case "RELF_CHRPROT": return "Protestant";
    case "RELF_CHRRC": return "Roman Catholic";
    case "RELF_CHRSALV": return "Salvation Army";
    case "RELF_CHRSDAY": return "Seventh Day Adventist";
    case "PPO_Y": return "Yes";
    case "PPO_N": return "No";
    case "LAC_Y": return "Yes";
    case "LAC_N": return "No";
    case "INT_Y": return "Yes";
    case "INT_N": return "No";
    case "MARITAL_CO": return "Cohabiting";
    case "TREAT_UC": return "Trial - Unconvicted";
    case "TREAT_UM": return "Remand - Unconvicted";
    case "TREAT_JR": return "Judges Respite - Convicted";
    case "TREAT_SEC10/3": return "Convicted Awaiting Sentence";
    case "TREAT_ST": return "Sentenced";
    case "TREAT_LF": return "Life/Indeterminate Sentence";
    case "TREAT_YO": return "Youth Offender";
    case "TREAT_FD": return "Fine Defaulter";
    case "TREAT_CP": return "Civil Prisoner";
    case "NAT_BRIT": return "British";
    case "NAT_IRISH": return "Irish";
    case "NAT_STATE": return "Stateless";
    case "NAT_UNKNOWN": return "Unknown";
    case "NAT_REF": return "Refused";
    case "NAT_AFGA": return "Afghan";
    case "NAT_ALBA": return "Albanian";
    case "NAT_ALGE": return "Algerian";
    case "NAT_AMER": return "American";
    case "NAT_ASM": return "American Samoan";
    case "NAT_ANDO": return "Andorran";
    case "NAT_ANGOL": return "Angolan";
    case "NAT_ANTIG": return "Antiguan, Barbudan";
    case "NAT_ARGEN": return "Argentine";
    case "NAT_AG": return "Anguillan";
    case "NAT_ARME": return "Armenian";
    case "NAT_AB": return "Aruban";
    case "NAT_AUSI": return "Australian";
    case "NAT_AUST": return "Austrian";
    case "NAT_AZERB": return "Azerbaijani";
    case "NAT_BAHA": return "Bahamian";
    case "NAT_BAHR": return "Bahraini";
    case "NAT_BANGL": return "Bangladeshi";
    case "NAT_BARB": return "Barbadian or Bajuns";
    case "NAT_LS": return "Basotho";
    case "NAT_BELA": return "Belarusian";
    case "NAT_BELG": return "Belgian";
    case "NAT_BELI": return "Belizean";
    case "NAT_BENI": return "Beninese";
    case "NAT_BM": return "Bermudian";
    case "NAT_BHUT": return "Bhutanese";
    case "NAT_BOLI": return "Bolivian";
    case "NAT_BOSNI": return "Bosnian, Herzegovinian";
    case "NAT_BRAZ": return "Brazilian";
    case "NAT_BRUN": return "Bruneian";
    case "NAT_BULG": return "Bulgarian";
    case "NAT_BURM": return "Burmese";
    case "NAT_HV": return "Burkinabe";
    case "NAT_BURU": return "Burundian";
    case "NAT_CAMB": return "Cambodian";
    case "NAT_CAMER": return "Cameroonian";
    case "NAT_CANA": return "Canadian";
    case "NAT_CAVER": return "Cape Verdian";
    case "NAT_KY": return "Caymanian";
    case "NAT_CF": return "Central African";
    case "NAT_CHAD": return "Chadian";
    case "NAT_CHIL": return "Chilean";
    case "NAT_CHINA": return "Chinese";
    case "NAT_CXR": return "Christmas Island";
    case "NAT_CCK": return "Cocos Islander";
    case "NAT_COK": return "Cook Islander";
    case "NAT_COLO": return "Colombian";
    case "NAT_COMO": return "Comoran";
    case "NAT_CONG": return "Congolese";
    case "NAT_COSRI": return "Costa Rican";
    case "NAT_CROAT": return "Croat";
    case "NAT_CUBA": return "Cuban";
    case "NAT_CYPR": return "Cypriot";
    case "NAT_CZEC": return "Czech";
    case "NAT_DANE": return "Danish";
    case "NAT_DJIB": return "Djibouti";
    case "NAT_DOMI": return "Dominican";
    case "NAT_DUTCH": return "Dutch";
    case "NAT_AN": return "Dutch Antillean";
    case "NAT_EATIM": return "East Timorese";
    case "NAT_ECUA": return "Ecuadorian";
    case "NAT_EGYP": return "Egyptian";
    case "NAT_EMIR": return "Emirian";
    case "NAT_EQUATO": return "Equatoguinean";
    case "NAT_ERI": return "Eritrean";
    case "NAT_ESTO": return "Estonian";
    case "NAT_ETHI": return "Ethiopian";
    case "NAT_FO": return "Faroese";
    case "NAT_FIJI": return "Fijian";
    case "NAT_FILIP": return "Filipino";
    case "NAT_FINN": return "Finnish";
    case "NAT_FREN": return "French";
    case "NAT_FG": return "French Guyanese";
    case "NAT_REU": return "Reunionese";
    case "NAT_ROMA": return "Romanian";
    case "NAT_RUSS": return "Russian";
    case "NAT_RWAN": return "Rwandan";
    case "NAT_SH": return "Saint Helenian";
    case "NAT_WA": return "Sahrawi";
    case "NAT_SALV": return "Salvadoran";
    case "NAT_SAMO": return "Samoan";
    case "NAT_SANM": return "San Marinese";
    case "NAT_STP": return "Sao Tomean";
    case "NAT_SAARA": return "Saudi Arabian";
    case "NAT_SECR": return "Serb or Croat";
    case "NAT_SENE": return "Senegalese";
    case "NAT_SEYC": return "Seychellois";
    case "NAT_SILE": return "Sierra Leonean";
    case "NAT_SING": return "Singaporean";
    case "NAT_SKOR": return "South Korean";
    case "NAT_SLENE": return "Slovene";
    case "NAT_SLOV": return "Slovak";
    case "NAT_SOAFR": return "South African";
    case "NAT_SOLO": return "Solomon Islander";
    case "NAT_SOMA": return "Somalian";
    case "NAT_SPAN": return "Spaniard";
    case "NAT_SRIL": return "Sri Lankan";
    case "NAT_STLU": return "Saint Lucian";
    case "NAT_SUDAN": return "Sudanese";
    case "NAT_SURIN": return "Surinamer";
    case "NAT_SWAZI": return "Swazi";
    case "NAT_SWEDE": return "Swede";
    case "NAT_SWIS": return "Swiss";
    case "NAT_SYRI": return "Syrian";
    case "NAT_TAIW": return "Taiwanese";
    case "NAT_TA": return "Tajikistani";
    case "NAT_TANZ": return "Tanzanian";
    case "NAT_THAI": return "Thai";
    case "NAT_TNGA": return "Tongan";
    case "NAT_TOGO": return "Togolese";
    case "NAT_TKL": return "Tokelauan";
    case "NAT_TRIN": return "Trinidadian, Tobagonian";
    case "NAT_TUNI": return "Tunisian";
    case "NAT_TURK": return "Turk";
    case "NAT_TU": return "Turkmen";
    case "NAT_TV": return "Tuvaluan";
    case "NAT_UGAN": return "Ugandan";
    case "NAT_UKRA": return "Ukrainian";
    case "NAT_URUG": return "Uruguayan";
    case "NAT_UZBE": return "Uzbekistani";
    case "NAT_VENE": return "Venezuelan";
    case "NAT_VC": return "Vincentian";
    case "NAT_VIET": return "Vietnamese";
    case "NAT_VG": return "Virgin Islander";
    case "NAT_YEMIN": return "Yemenite";
    case "NAT_ZAM": return "Zambian";
    case "NAT_ZIM": return "Zimbabwean";
    case "APPEAR_S": return "S";
    case "FACE_FAT": return "Fat";
    case "FACE_THIN": return "";
    case "SEXO_OTH": return "Other";
    case "SEXO_ND": return "Not Disclosed";
    case "NAT_KOS": return "Kosovan";
    case "NAT_CONR": return "Congolese (Congo, Republic of)";
    case "NAT_COND": return "Congolese (Congo, Democratic Republic)";
    case "NAT_MNE": return "Montenegrin";
    case "RELF_OORTH": return "Oriental Orthodox";
    case "RELF_EORTH": return "Eastern Orthodox";
    case "DIET_PRGNT": return "Medical - Pregnant";
    case "DIET_DFR": return "Medical - Dairy Free";
    default: return x;
  }
};

refData.movementReason = x => {
  switch (`${x}`) {
    case "REL_REL": return "Released";
    case "ADM_CRT": return "COURT";
    case "ADM_JAIL": return "JAIL";
    case "ADM_RECA": return "Recapture";
    case "ADM_TRN": return "TRANSFER";
    case "CRT_CRT": return "Court Appearance";
    case "CRT_CONF": return "CONFERENCE";
    case "REL_DISC": return "DISCHARGED";
    case "REL_ER": return "Executive Release Sec 32 CJA 1982";
    case "REL_MED": return "MEDICAL";
    case "REL_ESCP": return "Escape";
    case "TRN_ADMIN": return "ADMINISTRATIVE";
    case "TAP_JAIL": return "ABSENCE FROM JAIL";
    case "CRI_INT": return "COMMUNITY REPORT IN";
    case "ADM_ADMN": return "Administrative";
    case "ADM_CCOM": return "CIVIL COMMITAL";
    case "ADM_IMMIG": return "IMMIGRATION ACT 1971 (AWAITING DEPORT)";
    case "ADM_FINE": return "FINE DEFAULTER";
    case "ADM_CLIF": return "CUSTODY FOR LIFE";
    case "ADM_DHMP": return "DETAINED AT HER MAJESTY'S PLEASURE-53(1)";
    case "ADM_SENT": return "IMPRISONMENT WITHOUT OPTION";
    case "ADM_DCYP": return "DETAINED UNDER 53(2) CY&P ACT";
    case "ADM_RMND": return "UNCONVICTED REMAND";
    case "ADM_PSUS": return "PARTLY SUSPENDED SENTENCE";
    case "ADM_CONR": return "CONVICTED UNSENTENCED";
    case "ADM_YDET": return "DETENTION IN A YOUNG OFFENDER INST.";
    case "ADM_RHDC": return "RECALL FROM HDC";
    case "ADM_HLF": return "HOME LEAVE FAILURE";
    case "ADM_LICR": return "LICENCE REVOKEE";
    case "ADM_PSYC": return "AWAITING REMOVAL TO PYSCHIATRIC HOSPITAL";
    case "ADM_RDTO": return "RECALL FROM DRUG TREATMENT ORDER";
    case "ADM_FOREIGN": return "TRANSFER FROM FORIEGN LOCN";
    case "TAP_FAC": return "FACILITY LICENCE";
    case "TAP_RESET": return "RESETTLEMENT";
    case "TAP_COMP": return "COMPASSIONATE";
    case "REL_AU": return "Appeal Upheld on Release";
    case "REL_BL": return "Bailed";
    case "REL_DD": return "Discharged End of Sentence and Deported";
    case "REL_DE": return "Deportation (No Sentence)";
    case "REL_EX": return "Extradition";
    case "REL_DEC": return "Died";
    case "TAP_HOSP": return "HOSPITAL APPOINTMENT";
    case "TAP_DENT": return "DENTAL APPOINTMENT";
    case "TRN_PROG": return "PROGRAM";
    case "TRN_RECAT": return "RE-CATEGORISATION";
    case "CRT_NA": return "Not to Appear Court Date (For Diary Only";
    case "CRT_19": return "Court Appearance - Police Product Order";
    case "CRT_22": return "Witness";
    case "CRT_AP": return "Discharge to Court on Appeal";
    case "CRT_AU": return "APPEAL UPHELD ON RELEASE";
    case "CRT_CA": return "Court Appearance";
    case "CRT_CT": return "Custody Time Limit";
    case "CRT_DC": return "Discharged to Court";
    case "CRT_F4": return "Unescorted Court Appearance";
    case "CRT_PR": return "Production of Unsentenced Inmate at Cour";
    case "CRT_APPEAR": return "APPEARANCE";
    case "CRT_DIR": return "DIRECTIONS";
    case "CRT_INTAKE": return "INTAKE";
    case "CRT_TRIAL": return "Trial";
    case "CRT_PDH": return "Plea and Directions Hearing";
    case "CRT_CAP": return "COURT APPEARANCE";
    case "CRT_SEN": return "SENTENCED";
    case "CRT_PS": return "Production (Sentence/Civil Custody)";
    case "TRN_AVIST": return "ACCUMULATED VISITS";
    case "TRN_OJ": return "Outside Jurisdiction";
    case "TRN_MED": return "Medical";
    case "TAP_MED": return "MEDICAL";
    case "INTER_INTER": return "Intermittent Custody";
    case "REL_WEND": return "WEEKENDERS";
    case "ADM_MED": return "MEDICAL";
    case "ADM_INT": return "Transfer In from Other Establishment";
    case "TRN_TRN": return "Transfer";
    case "ADM_A": return "Late Return (Voluntary)";
    case "ADM_B": return "Recall From HDC";
    case "ADM_C": return "Civil Committal";
    case "ADM_D": return "Sentenced to Death";
    case "ADM_E": return "Detained Immigration Act 71 -Wait Deport";
    case "ADM_F": return "Fine Defaulter";
    case "ADM_G": return "Custody For Life CJA 1982";
    case "ADM_H": return "Home Leave Failure";
    case "ADM_I": return "Imprisonment Without Option";
    case "ADM_J": return "Detained at HM's Pleasure Sec53(1) C&YP";
    case "ADM_K": return "Detained under S53(2) C&YP Act";
    case "ADM_L": return "Licence Revokee";
    case "ADM_M": return "Transfer in from other Establishment";
    case "ADM_N": return "Unconvicted Remand";
    case "ADM_O": return "Awaiting Removal to Psychiatric Hospital";
    case "ADM_P": return "Partly Suspended Sentence";
    case "ADM_Q": return "Overnight Stopover Enroute to Accumulati";
    case "ADM_R": return "Returns";
    case "ADM_S": return "Overnight Stopover b4 Transfer to Estab";
    case "ADM_T": return "Transfer in from Foreign Prison";
    case "ADM_U": return "Late Return (Involuntary)";
    case "ADM_V": return "Convicted Unsentenced";
    case "ADM_W": return "Detention in a YOI";
    case "ADM_Y": return "Recall from DTO";
    case "ADM_Z": return "Sameday Stopover Enroute to Other Estab";
    case "ADM_24": return "Recall from Intermittent Custody";
    case "ADM_25": return "Indeterminate Sentence for Public Prot";
    case "ADM_26": return "Extended Sentence for Public Protection";
    case "ADM_27": return "Custody For Life under 18 Sec93";
    case "ADM_29": return "C/F Life at least 18 & under 21 Sec 94";
    case "CRT_VL": return "Video Link (Court Appearance)";
    case "REL_99": return "Discharge Not For Release";
    case "REL_AR": return "AUTO RELEASE UNDER 12 MTH SHORT TERMERS";
    case "REL_AS": return "Accumulated Visits with Stopover";
    case "REL_AV": return "Accumulated Visits";
    case "REL_CR": return "Conditional Release (CJA91)- Sh Term>1yr";
    case "REL_D1": return "DTO Discharge 2 Months Early";
    case "REL_D2": return "DTO Discharge 1 Month Early";
    case "REL_D3": return "DTO Discharge Mid Term Transfer";
    case "REL_D6": return "DTO Re-Release";
    case "REL_DA": return "Discharged on Appeal from Court";
    case "REL_DL": return "Deportation Licencees(Parole/Life/HMP)";
    case "REL_DS": return "Discontinuance/Charges Withdrawn";
    case "REL_HD": return "HDC Re-Release Conditional";
    case "REL_HE": return "HDC Re-Release Unconditional";
    case "REL_HP": return "Final Discharge to Hospital-Psychiatric";
    case "REL_HR": return "HDC Conditional Release";
    case "REL_HU": return "HDC Unconditional Release";
    case "REL_NP": return "Non Parole Release Date";
    case "REL_PF": return "Paid Fine";
    case "REL_PX": return "Final Parole inc YOI Released On Licence";
    case "REL_RE": return "Repatriated";
    case "REL_RW": return "Royal Warrant-Free Pardon/Compassionate";
    case "REL_SC": return "Sentence Completed/Contempt Purged";
    case "REL_UAL": return "Abscond";
    case "TAP_1": return "Visit Dying Relative";
    case "TAP_2": return "Funeral";
    case "TAP_3": return "Childcare Resettlement Licence";
    case "TAP_4": return "Other Compassionate Reason";
    case "TAP_5": return "Outside Hospital Attendance";
    case "TAP_6": return "External Sporting Activity";
    case "TAP_7": return "External Education Classes";
    case "TAP_8": return "Community Service Volunteer";
    case "TAP_9": return "Probation Service Workshops";
    case "TAP_10": return "Adventure And Social Welfare";
    case "TAP_11": return "Interview For Half Way House";
    case "TAP_12": return "Visit to Outside Hostel for Assessment";
    case "TAP_13": return "Employment Interview";
    case "TAP_14": return "Long Home Leave";
    case "TAP_15": return "Terminal Home Leave";
    case "TAP_16": return "Short Home Leave";
    case "TAP_17": return "Pre Parole Leave";
    case "TAP_18": return "Marriage";
    case "TAP_20": return "Other RDR Linked to Sent/Reset Plan";
    case "TAP_21": return "Other (i.e. IPV, ID Parades etc)";
    case "TAP_C1": return "Primary Carer";
    case "TAP_C2": return "Urgent Domestic Or Family Needs";
    case "TAP_C4": return "Wedding/Civil Ceremony";
    case "TAP_C5": return "Medical/Dental Outpatient Appointment";
    case "TAP_C6": return "Medical/Dental Inpatient Appointment";
    case "TAP_C9": return "Attend Religious Service";
    case "TAP_F1": return "Training";
    case "TAP_F2": return "Education";
    case "TAP_F3": return "Reparation Projects";
    case "TAP_F4": return "Unescorted Court Appearance";
    case "TAP_F6": return "Visit Legal Adviser (Unescorted)";
    case "TAP_F7": return "Working Out Schemes";
    case "TAP_F8": return "Job Interview (Under 12m)";
    case "TAP_F9": return "Interview For Hostel Accommodation";
    case "TAP_FA": return "Seeking Other Accommodation (Under 12m)";
    case "TAP_FB": return "Accommodation Related";
    case "TAP_FC": return "Adventure Training";
    case "TAP_FD": return "External Team Sports";
    case "TAP_FE": return "Driving Lessons";
    case "TAP_FF": return "Opening Bank Accounts";
    case "TAP_FR": return "Deport of F/N under Early Removal Scheme";
    case "TAP_I1": return "Local Visit (Incentive Scheme)";
    case "TAP_IM": return "Intermittent Custody Final Release";
    case "TAP_PC": return "Police Production";
    case "TAP_R1": return "Job Interview";
    case "TAP_R2": return "Paid Work Placements";
    case "TAP_R3": return "Maintaining Family Ties";
    case "TAP_R5": return "Seeking Other Accommodation";
    case "TAP_R6": return "Pre-Parole Release";
    case "TAP_R4": return "Interview for Hostel Accommodation";
    case "TAP_R7": return "Community Service Volunteer";
    case "TAP_R8": return "Probation Service Workshop";
    case "TAP_R9": return "Overnight Resettlement Unit/Pres Hostel";
    case "TAP_RO": return "Resettlement Overnight Release";
    case "TAP_TAP": return "ROTL";
    case "TRN_28": return "28 Day Lie Down";
    case "TRN_ACCVISIT": return "Accumulated Visits";
    case "TRN_APPEALS": return "Appeals";
    case "TRN_COMP": return "Compassionate Transfer";
    case "TRN_INT": return "Internal Transfer";
    case "TRN_NOTR": return "Normal Transfer";
    case "TRN_OTHER": return "Other inc Change Of Status";
    case "TRN_OVCROW": return "Overcrowding Draft";
    case "TRN_PRES": return "Pre Release Employment Scheme";
    case "TRN_PROAT": return "Programme Attendance";
    case "TRN_PROD": return "For Production";
    case "TRN_SEC": return "Security Reasons";
    case "TAP_SP": return "Helping Police With Enquiries";
    case "CRT_CRI": return "Court Review";
    case "CRT_NEWTON": return "Newton Hearing";
    case "CRT_BAIL": return "Bail application";
    case "CRT_BREACH": return "Breach hearing";
    case "CRT_SENT": return "Sentencing";
    case "CRT_COM": return "Committal Hearing";
    case "CRT_REM": return "Remittal Hearing";
    case "TAP_ACCVISIT": return "Accumulated Visits";
    case "TAP_C7": return "Visit Dying Relative";
    case "TAP_EL": return "End of Custody Licence (ECL)";
    case "TAP_ELR": return "Recall from End of Custody Licence (ECL)";
    case "ADM_TRNCRT": return "TRANSFER VIA COURT";
    case "ADM_TRNTAP": return "TRANSFER VIA TEMPORARY RELEASE";
    case "REL_UAL_ECL": return "ABSCOND END OF CUSTODY LICENCE";
    case "REL_MRG": return "Administrative Release due to Merge";
    case "REL_D5": return "DTO 2 Months Late Transfer";
    case "REL_D4": return "DTO Late Transfer";
    case "REL_IF": return "Intermittent Custody Final Release";
    case "REL_HC": return "Invalid Commital/Habeas Corpus";
    case "REL_PD": return "Post Recall Release";
    case "REL_CE": return "Conditional Release Extended Sentence CJ";
    case "TAP_IR": return "Intermittent Custody Release";
    case "ADM_INTER": return "Intermittent Custody";
    case "REL_BD": return "Bailed Detainee";
    case "TRN_AS": return "Accumulated Visits with Stopover";
    case "REL_NCS": return "NON CUSTODIAL SENTENCE";
    case "TAP_C3": return "Funerals And Deaths";
    case "ADM_ELR": return "Recall from End of Custody Licence (ECL)";
    case "REL_NG": return "NOT GUILTY";
    case "TAP_OPA": return "Outside Prison Activity";
    case "REL_ETR": return "ERS/TERS Release";
    case "ADM_ETB": return "ERS/TERS Breach";
    case "TAP_ET": return "Education or Training";
    case "TAP_SE": return "Other Security Escort";
    case "TAP_PAP": return "Prisoner Apprenticeships Pathway";
    case "TAP_LTX": return "Court/Legal/Police/Prison Transfer";
    case "TAP_YMI": return "Meetings and Interviews";
    case "TAP_YRDR": return "Resettlement Day Release";
    case "TAP_YOTR": return "Other Temp Rel linked to Sent/Reset plan";
    case "TAP_PWP": return "Paid Work Placements (Youth)";
    case "TAP_UPW": return "Unpaid Work Placements";
    default: return x;
  }
};

refData.escort = x => {
  switch (`${x}`) {
    case "A": return "Accompanied";
    case "GEOAME": return "GeoAmey";
    case "GROUP4": return "Group 4 Securicor";
    case "HMPS": return "H.M.P Establishment";
    case "L": return "Prison Officer Escort (Local)";
    case "N": return "Prison Officer Escort (National)";
    case "P": return "Police Escort";
    case "PECS": return "Prisoner Escort Contractors (Other)";
    case "PREM": return "Premier";
    case "REL": return "Reliance";
    case "U": return "Unescorted";
    case "Z": return "Other (Immigration etc.)";
    default: return x;
  }
};

refData.refDataTemplate = x => {
  switch (`${x}`) {
    default: return x;
  }
};



module.exports = refData;
